language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: clang

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get update
  - sudo apt-get install qt5-qmake libqt5test5

script:
  - qmake -v
  - cd ./build
  - qmake -o Makefile src.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX
  - qmake -o MakefileTest test.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX
  - make
  - make -f MakefileTest
  - export LD_LIBRARY_PATH=../output:$LD_LIBRARY_PATH && ../output/test

notifications:
  slack:
    on_success: never
    on_failure: never
