language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install libqt5test5 qt5-qmake

script:
  - qmake -v
  - cd .build
  - qmake src.pro
  - make

notifications:
  slack:
    on_success: never
    on_failure: never
