language: cpp
dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

install:
  - sudo apt-get update
  - sudo apt-get install qt5-qmake libqt5test5

script:
  - qmake -v
  - cd ./build
  - qmake -o Makefile src.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX
  - qmake -o MakefileTest test.pro QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_LINK=$CXX
  - make && make -f MakefileTest && export LD_LIBRARY_PATH=../output:$LD_LIBRARY_PATH && ../output/test

notifications:
  slack:
    on_success: never
    on_failure: never
